title: Портфолио
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Включаем поиск
search_enabled: true

# Настройки меню
aux_links:
  "GitHub Repository":
    - https://github.com/ND-love/portfolio

url: "https://nd-love.github.io/portfolio"