site_name: Портфолию Д.Р.
site_url: https://github.com/ND-love

# --- ТЕМА И ВНЕШНИЙ ВИД ---
theme:
  name: material
  language: ru
  custom_dir: docs 
  
  palette:
    # Темная тема (VS Code Style)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Светлая тема
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  # --- НАСТРОЙКИ МЕНЮ (ДЕРЕВО) ---
  features:
    - navigation.expand       # Стрелочки раскрытия
    - navigation.instant
    - navigation.tracking     # Меню следит за тобой
    - navigation.top
    - content.code.copy

# --- CSS СТИЛИ ---
extra_css:
  - stylesheets/extra.css

# --- MARKDOWN ---
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

plugins:
  - search

# --- САМОЕ ВАЖНОЕ: РУЧНОЕ ДЕРЕВО ---
# Здесь мы строим структуру сами.
# Формат: "- Название в меню: путь/к/файлу.md"
nav:
  - 'Мое портфолио': index.md
  
  - 'bWAPP Labs':
      - 'Injection (Low)': 'bWAPP/A1 - Injection - low/SQL Injection (GETSelect).md'
      
  - 'PortSwigger Labs':
      - 'SQL Injection':
          - 'Введение': 'PortSwigger Labs/SQL Injection/index.md'
      - 'Шпаргалка (Cheat Sheet)': 'PortSwigger Labs/SQL Injection Cheat Sheet.md'